site_name: Minecraft in python

nav:
  - Home: index.md
  - Install resource: install-res.md
  - Install game: install-game.md
  - About:
    - Contributing: about/contributing.md
    - License: about/license.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - javascript
    - python

copyright: Copyright &copy 2020 Minecraft-in-python<br>&nbsp;&nbsp;All Right Reserved.

markdown_extensions:
  - admonition
