site_name: Minecraft in python

nav:
  - Home: index.md

theme: readthedocs

copyright: Copyright &copy 2020 Minecraft-in-python<br>&nbsp;&nbsp;All Right Reserved.

markdown_extensions:
  - admonition
